const data = {
  products: [
    {
      name: ' mukash habesha kemis',
      slug: 'mukash-habesha-kemis',
      category: 'kemis',
      image: '/images/p1.jpg',
      price: 500,
      countInStock: 10,
      brand: 'mukash fashion',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality kemis',
    },

    {
      name: ' habeshawi habesha kemis',
      slug: 'habeshawi-habesha-kemis',
      category: 'kemis',
      image: '/images/p3.jpg',
      price: 5000,
      countInStock: 0,
      brand: 'habeshawi fashion',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality kemis',
    },
    {
      name: ' mukash shifon',
      slug: 'mukash-shifon',
      category: 'kemis',
      image: '/images/p4.jpeg',
      price: 3000,
      countInStock: 20,
      brand: 'mukash fashion',
      rating: 8.5,
      numReviews: 13,
      description: 'high quality kemis',
    },
    {
      name: 'habeshawi kaba',
      slug: 'habeshawi kaba',
      category: 'kaba',
      image: '/images/p2.jpg',
      price: 5000,
      countInStock: 10,
      brand: 'mukash fashion',
      rating: 6.5,
      numReviews: 15,
      description: 'high quality kaba',
    },
  ],
};
export default data;
